eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: HotelService
    
# okta authentication configure
okta:
  oauth2:
    issuer: https://dev-13622868.okta.com/oauth2/default
    audience: api://default
    


